import "../../../just/libafl-qemu.just"

ARCH := env("ARCH", "arm")
FUZZER_NAME := "qemu_nesting"
KERNEL := env("KERNEL")
INITRD := env("INITRD")

build:
    cargo build \
        --profile {{ PROFILE }} \
        --no-default-features \
        --features std,breakpoint,{{ ARCH }} \
        --target-dir {{ TARGET_DIR }}

run: (build)
    {{ BUILD_DIR / "qemu_nesting" }} \
        -machine virt,virtualization=on,gic-version=3 \
        -cpu cortex-a57 \
        -m 1024 \
        -monitor null \
        -kernel {{ KERNEL }} \
        -initrd {{ INITRD }} \
        -serial null \
        -nographic \
        -append "console=ttyAMA0 rdinit=/bin/sh"
